

export const UNREGISTERED_COURSES_LOADING = 'UNREGISTERED_DISHES_LOADING';
export const UNREGISTERED_COURSES_FAILED = 'UNREGISTERED_DISHES_FAILED';
export const ADD_UNREGISTERED_COURSES = 'ADD_UNREGISTERED_DISHES';


